INSERT INTO DEMANDADO (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, EXPEDIENTE_ID, SEXO_ID) VALUES (45789011, 'Evelio Alonso', 'Quintana', 'Barboza', 'Av. Los Fresnos 110, La Molina, Lima', 1, 2);
INSERT INTO DEMANDADO (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, EXPEDIENTE_ID, SEXO_ID) VALUES (56890123, 'Sarita del Mar', 'Carrasco', 'Ugarte', 'Jr. Los Álamos 225, San Isidro, Lima', 2, 1);
INSERT INTO DEMANDADO (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, EXPEDIENTE_ID, SEXO_ID) VALUES (67901234, 'Nicanor', 'Vilchez', 'Castañeda', 'Calle Los Pinos 334, Miraflores, Lima', 3, 2);
INSERT INTO DEMANDADO (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, EXPEDIENTE_ID, SEXO_ID) VALUES (78901245, 'Dalia María', 'Mamani', 'Rojas', 'Av. Los Eucaliptos 443, Surco, Lima', 4, 1);
INSERT INTO DEMANDADO (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, EXPEDIENTE_ID, SEXO_ID) VALUES (89012356, 'Ulises Gabriel', 'Pajares', 'Salcedo', 'Jr. Los Cedros 554, San Borja, Lima', 5, 2);
INSERT INTO DEMANDADO (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, EXPEDIENTE_ID, SEXO_ID) VALUES (90123467, 'Zarela', 'Oviedo', 'Chávez', 'Calle Los Robles 696, Jesús María, Lima', 6, 1);
INSERT INTO DEMANDADO (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, EXPEDIENTE_ID, SEXO_ID) VALUES (01234578, 'Froilán José', 'Paredes', 'Zúñiga', 'Av. Los Ángeles 787, Los Olivos, Lima', 7, 2);
INSERT INTO DEMANDADO (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, EXPEDIENTE_ID, SEXO_ID) VALUES (12345689, 'Belinda Rosa', 'Castañeda', 'Vera', 'Av. El Sol 848, Cusco', 8, 1);
INSERT INTO DEMANDADO (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, EXPEDIENTE_ID, SEXO_ID) VALUES (23456790, 'Teódulo', 'Vargas', 'Mendoza', 'Calle San Pedro 914, Arequipa', 9, 2);
INSERT INTO DEMANDADO (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, EXPEDIENTE_ID, SEXO_ID) VALUES (34567801, 'Yolanda Carmen', 'Quispe', 'Valdivia', 'Jr. Los Andes 158, Trujillo', 10, 1);

