INSERT INTO FORMRENIEC (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, ESTADOCIVIL_ID, GRADOINSTRUCCION_ID, SEXO_ID) VALUES (47856231, 'Carlos Alberto', 'Gonzales', 'Paredes', 'Av. Arequipa 345, Lima', 1, 3, 2);
INSERT INTO FORMRENIEC (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, ESTADOCIVIL_ID, GRADOINSTRUCCION_ID, SEXO_ID) VALUES (39284756, 'Maria Luisa', 'Quispe', 'Huaman', 'Jr. Los Pinos 784, Lima', 2, 2, 1);
INSERT INTO FORMRENIEC (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, ESTADOCIVIL_ID, GRADOINSTRUCCION_ID, SEXO_ID) VALUES (58392047, 'Juan', 'Ramirez', 'Vargas', 'Calle Los Olivos 123, Lima', 3, 4, 2);
INSERT INTO FORMRENIEC (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, ESTADOCIVIL_ID, GRADOINSTRUCCION_ID, SEXO_ID) VALUES (69483720, 'Rosa Maria', 'Torres', 'Fernandez', 'Av. El Sol 908, Lima', 1, 1, 1);
INSERT INTO FORMRENIEC (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, ESTADOCIVIL_ID, GRADOINSTRUCCION_ID, SEXO_ID) VALUES (78563492, 'Pedro', 'Mendoza', 'Lopez', 'Calle San Martin 456, Lima', 4, 3, 2);
INSERT INTO FORMRENIEC (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, ESTADOCIVIL_ID, GRADOINSTRUCCION_ID, SEXO_ID) VALUES (89674523, 'Ana', 'Castillo', 'Gutierrez', 'Av. Larco 789, Lima', 2, 2, 1);
INSERT INTO FORMRENIEC (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, ESTADOCIVIL_ID, GRADOINSTRUCCION_ID, SEXO_ID) VALUES (90785634, 'Luis Enrique', 'Perez', 'Salas', 'Jr. Los Eucaliptos 321, Lima', 3, 1, 2);
INSERT INTO FORMRENIEC (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, ESTADOCIVIL_ID, GRADOINSTRUCCION_ID, SEXO_ID) VALUES (61827394, 'Julia', 'Diaz', 'Moreno', 'Calle Los Ficus 654, Chiclayo', 1, 4, 1);
INSERT INTO FORMRENIEC (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, ESTADOCIVIL_ID, GRADOINSTRUCCION_ID, SEXO_ID) VALUES (72938465, 'Roberto', 'Vega', 'Ortiz', 'Av. Los Heroes 432, Puno', 4, 3, 2);
INSERT INTO FORMRENIEC (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, ESTADOCIVIL_ID, GRADOINSTRUCCION_ID, SEXO_ID) VALUES (84049576, 'Carmen', 'Rojas', 'Maldonado', 'Jr. Las Magnolias 231, Iquitos', 2, 1, 1);

