INSERT INTO JUZGADOPAZLETRADO (DIRECCION) VALUES ('Av. Javier Prado 3030, San Borja, Lima, Lima');
INSERT INTO JUZGADOPAZLETRADO (DIRECCION) VALUES ('Av. Manuel Holguin 2945, San Borja, Lima, Lima');
INSERT INTO JUZGADOPAZLETRADO (DIRECCION) VALUES ('Av. Aviacion 6762, San Borja, Lima, Lima');
INSERT INTO JUZGADOPAZLETRADO (DIRECCION) VALUES ('Jr. Camana 421, Cercado de Lima, Lima, Lima'),
INSERT INTO JUZGADOPAZLETRADO (DIRECCION) VALUES ('Av. Arequipa 1123, Lince, Lima, Lima'),
INSERT INTO JUZGADOPAZLETRADO (DIRECCION) VALUES ('Calle Berlin 345, Miraflores, Lima, Lima'),
INSERT INTO JUZGADOPAZLETRADO (DIRECCION) VALUES ('Av. Universitaria 2065, San Miguel, Lima, Lima'),
INSERT INTO JUZGADOPAZLETRADO (DIRECCION) VALUES ('Jr. De la Unión 987, Cercado de Lima, Lima, Lima'),
INSERT INTO JUZGADOPAZLETRADO (DIRECCION) VALUES ('Av. El Ejercito 475, Magdalena del Mar, Lima, Lima'),
INSERT INTO JUZGADOPAZLETRADO (DIRECCION) VALUES ('Calle Los Tulipanes 284, La Molina, Lima, Lima'),
