INSERT INTO "FormRENIEC" (dni, nombres, apellidos, nombreCompleto, direccion, sexoId, estadocivilId, gradoInstruccionId) VALUES (47856231, 'Carlos Alberto', 'Gonzales Paredes', 'Carlos Alberto Gonzales Paredes', 'Av. Arequipa 345, Lima', 1, 3, 2);
INSERT INTO "FormRENIEC" (dni, nombres, apellidos, nombreCompleto, direccion, sexoId, estadocivilId, gradoInstruccionId) VALUES (39284756, 'Maria Luisa', 'Quispe Huaman', 'Maria Luisa Quispe Huaman', 'Jr. Los Pinos 784, Lima', 2, 2, 1);
INSERT INTO "FormRENIEC" (dni, nombres, apellidos, nombreCompleto, direccion, sexoId, estadocivilId, gradoInstruccionId) VALUES (58392047, 'Juan', 'Ramirez Vargas', 'Juan Ramirez Vargas', 'Calle Los Olivos 123, Lima', 3, 4, 2);
INSERT INTO "FormRENIEC" (dni, nombres, apellidos, nombreCompleto, direccion, sexoId, estadocivilId, gradoInstruccionId) VALUES (69483720, 'Rosa Maria', 'Torres Fernandez', 'Rosa Maria Torres Fernandez', 'Av. El Sol 908, Lima', 2, 1, 1);
INSERT INTO "FormRENIEC" (dni, nombres, apellidos, nombreCompleto, direccion, sexoId, estadocivilId, gradoInstruccionId) VALUES (78563492, 'Pedro', 'Mendoza Lopez', 'Pedro Mendoza Lopez', 'Calle San Martin 456, Lima', 1, 3, 2);
INSERT INTO "FormRENIEC" (dni, nombres, apellidos, nombreCompleto, direccion, sexoId, estadocivilId, gradoInstruccionId) VALUES (89674523, 'Ana', 'Castillo Gutierrez', 'Ana Castillo Gutierrez', 'Av. Larco 789, Lima', 3, 2, 1);
INSERT INTO "FormRENIEC" (dni, nombres, apellidos, nombreCompleto, direccion, sexoId, estadocivilId, gradoInstruccionId) VALUES (90785634, 'Luis Enrique', 'Perez Salas', 'Luis Enrique Perez Salas', 'Jr. Los Eucaliptos 321, Lima', 3, 1, 2);
INSERT INTO "FormRENIEC" (dni, nombres, apellidos, nombreCompleto, direccion, sexoId, estadocivilId, gradoInstruccionId) VALUES (61827394, 'Julia', 'Diaz Moreno', 'Julia Diaz Moreno', 'Calle Los Ficus 654, Chiclayo', 2, 4, 1);
INSERT INTO "FormRENIEC" (dni, nombres, apellidos, nombreCompleto, direccion, sexoId, estadocivilId, gradoInstruccionId) VALUES (72938465, 'Roberto', 'Vega Ortiz', 'Roberto Vega Ortiz', 'Av. Los Heroes 432, Puno', 1, 3, 2);
INSERT INTO "FormRENIEC" (dni, nombres, apellidos, nombreCompleto, direccion, sexoId, estadocivilId, gradoInstruccionId) VALUES (84049576, 'Carmen', 'Rojas Maldonado', 'Carmen Rojas Maldonado', 'Jr. Las Magnolias 231, Iquitos', 2, 1, 1);

