INSERT INTO GRADOINSTRUCCION (NOMBRE) VALUES ('EDUCACION INICIAL');
INSERT INTO GRADOINSTRUCCION (NOMBRE) VALUES ('EDUCACION PRIMARIA');
INSERT INTO GRADOINSTRUCCION (NOMBRE) VALUES ('EDUCACION SECUNDARIA');
INSERT INTO GRADOINSTRUCCION (NOMBRE) VALUES ('EDUCACION SUPERIOR');