INSERT INTO PERSONA_NATURAL (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, EXPEDIENTE_ID, SEXO_ID) VALUES (47329101, 'Renato Alonso', 'Quispe', 'Huamán', 'Av. Los Precursores 345, San Miguel, Lima', 1, 1);
INSERT INTO PERSONA_NATURAL (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, EXPEDIENTE_ID, SEXO_ID) VALUES (57329102, 'Yadira', 'Castañeda', 'Vilca', 'Jr. Los Nogales 123, Lince, Lima', 2, 1);
INSERT INTO PERSONA_NATURAL (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, EXPEDIENTE_ID, SEXO_ID) VALUES (67329103, 'Eusebio', 'Mendoza', 'Cabrera', 'Calle Los Pinos 456, Miraflores, Lima', 3, 2);
INSERT INTO PERSONA_NATURAL (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, EXPEDIENTE_ID, SEXO_ID) VALUES (77329104, 'Flor de María', 'Paredes', 'Salas', 'Av. La Marina 789, Pueblo Libre, Lima', 4, 1);
INSERT INTO PERSONA_NATURAL (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, EXPEDIENTE_ID, SEXO_ID) VALUES (87329105, 'Sandro', 'Vergara', 'Zegarra', 'Jr. Los Ficus 101, La Molina, Lima', 5, 2);
INSERT INTO PERSONA_NATURAL (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, EXPEDIENTE_ID, SEXO_ID) VALUES (97329106, 'Luzmila', 'Cordova', 'Tello', 'Calle Los Olivos 202, Surco, Lima', 6, 1);
INSERT INTO PERSONA_NATURAL (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, EXPEDIENTE_ID, SEXO_ID) VALUES (08329107, 'Cecilio', 'Farfán', 'Bustamante', 'Av. Los Heroes 303, San Juan de Miraflores, Lima', 7, 2);
INSERT INTO PERSONA_NATURAL (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, EXPEDIENTE_ID, SEXO_ID) VALUES (18329108, 'Brisa del Mar', 'Valdivia', 'Ochoa', 'Av. Sol Naciente 404, Cusco', 8, 1);
INSERT INTO PERSONA_NATURAL (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, EXPEDIENTE_ID, SEXO_ID) VALUES (28329109, 'Gonzalo Ulises', 'Saldaña', 'Maldonado', 'Calle San Martín 505, Arequipa', 9, 2);
INSERT INTO PERSONA_NATURAL (DNI, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, EXPEDIENTE_ID, SEXO_ID) VALUES (38329110, 'Marina Luz', 'Orozco', 'Vera', 'Jr. Las Magnolias 606, Trujillo', 10, 1);


INSERT INTO "PersonaNatural" (username, password, nombres, apellidos, nombrecompleto, dni, correo, sexoId, expedienteId) 
values ('renatoquispe', 'renatoq', 'Renato Alonso', 'Quispe Huamán', 'Renato Alonso Quispe Huamán', 47329101, 'renatoquispe@gmail.com', 1, 1)


INSERT INTO "PERSONA_NATURAL" ("DNI", NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, DIRECCION, EXPEDIENTE_ID, SEXO_ID) VALUES (47329101, 'Renato Alonso', 'Quispe', 'Huamán', 'Av. Los Precursores 345, San Miguel, Lima', 1, 1);