INSERT INTO ESTADOCIVIL (NOMBRE) VALUES ('SOLTERO');
INSERT INTO ESTADOCIVIL (NOMBRE) VALUES ('CASADO');
INSERT INTO ESTADOCIVIL (NOMBRE) VALUES ('VIUDO');
INSERT INTO ESTADOCIVIL (NOMBRE) VALUES ('DIVORCIADO');